# Permalinks
permalink:           pretty
markdown:            kramdown

# Setup
title:               Siavash Khallaghi
tagline:             Machine Learning, Computer Vision, Data Sciences
url:                 http://ece.ubc.ca/~siavashk
baseurl:             ""
paginate:            1
baseurl:             ""
highlighter:         rouge

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Siavash Khallaghi"
resume_title:                   "Data Scientist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "khallagh65@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_address:         "Clarius Mobile Health, 3605 Gilmore Way, Burnaby, BC"

resume_header_contact_info:     "Clarius Mobile Health, 3605 Gilmore Way, Burnaby • khallagh65@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I provide machine learning and image processing solutions for medical and computer vision challenges. I graduated from a PhD prgram at the Univeristy of British Columbia. As part of my thesis, I developed image registration techniques for prostate interventions. Since graduation, I have worked as a machine learning scientist at various start-up companies.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/siavashk"
  resume_linkedin_url:          "https://www.linkedin.com/in/siavash-khallaghi-51772129/"
  resume_website_url:           "http://www.ece.ubc.ca/~siavashk/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

pages_list:
  About: '/about'
  Archive: '/archive'

# About/contact
author:
  name:              Siavash Khallaghi
  url:               https://twitter.com/khallagh65
  email:             khallagh65@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              github.com/siavashk/siavashk.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
